// <auto-generated />
using System;
using AuthorizationService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthorizationService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuthzDbContext))]
    [Migration("20251124185620_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasComment("Идентификатор");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code")
                        .HasComment("Код");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Описание");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Наименование");

                    b.Property<Guid>("ResourceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_type_id")
                        .HasComment("Тип ресурса");

                    b.HasKey("Id")
                        .HasName("pk_permission_id");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex(new[] { "Code" }, "idx_code_permissions")
                        .IsUnique();

                    b.ToTable("permissions", null, t =>
                        {
                            t.HasComment("Разрешения");
                        });
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasComment("Идентификатор");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id")
                        .HasComment("Внешний доменный идентификатор");

                    b.Property<Guid?>("OwnerSubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_subject_id")
                        .HasComment("Идентификатор владельца");

                    b.Property<Guid>("ResourceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_type_id")
                        .HasComment("Идентификатор типа ресурса");

                    b.HasKey("Id")
                        .HasName("pk_resource_id");

                    b.HasIndex("OwnerSubjectId");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("resources", null, t =>
                        {
                            t.HasComment("Ресурсы");
                        });
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.ResourceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasComment("Идентификатор");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code")
                        .HasComment("Код");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Описание");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Наименование");

                    b.HasKey("Id")
                        .HasName("pk_resource_type_id");

                    b.HasIndex(new[] { "Code" }, "idx_code_resource_types")
                        .IsUnique();

                    b.ToTable("resource_types", null, t =>
                        {
                            t.HasComment("Типы ресурсов");
                        });
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasComment("Идентификатор");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code")
                        .HasComment("Код");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Описание");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Наименование");

                    b.Property<Guid>("ResourceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_type_id")
                        .HasComment("Тип ресурса");

                    b.HasKey("Id")
                        .HasName("pk_role_id");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex(new[] { "Code" }, "idx_code_roles")
                        .IsUnique();

                    b.ToTable("roles", null, t =>
                        {
                            t.HasComment("Роли");
                        });
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasComment("Идентификатор роли");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id")
                        .HasComment("Идентификатор разрешения");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_id_permission_id");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", null, t =>
                        {
                            t.HasComment("Связь ролей с разрешениями");
                        });
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()")
                        .HasComment("Идентификатор");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()")
                        .HasComment("Дата создания");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("now()")
                        .HasComment("Дата последнего обновления");

                    b.Property<Guid>("UserExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_external_id")
                        .HasComment("Внешний идентификатор пользователя");

                    b.HasKey("Id")
                        .HasName("pk_subject_id");

                    b.HasIndex(new[] { "UserExternalId" }, "idx_user_external_id_subjects")
                        .IsUnique();

                    b.ToTable("subjects", null, t =>
                        {
                            t.HasComment("Субъекты(пользователи)");
                        });
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.SubjectRole", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id")
                        .HasComment("Идентификатор субъекта(пользователя)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasComment("Идентификатор роли");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id")
                        .HasComment("Идентификатор ресурса");

                    b.Property<DateTime?>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from")
                        .HasDefaultValueSql("now()")
                        .HasComment("Дата выдачи роли");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to")
                        .HasComment("Дата деактивирования роли");

                    b.HasKey("SubjectId", "RoleId", "ResourceId")
                        .HasName("pk_subject_id_role_id_resource_id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("RoleId");

                    b.ToTable("subject_roles", null, t =>
                        {
                            t.HasComment("Связь субъекта с ролями");
                        });
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.Permission", b =>
                {
                    b.HasOne("AuthorizationService.Infrastructure.Persistence.Entities.ResourceType", "ResourceType")
                        .WithMany("Permissions")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.Resource", b =>
                {
                    b.HasOne("AuthorizationService.Infrastructure.Persistence.Entities.Subject", "OwnerSubject")
                        .WithMany("Resources")
                        .HasForeignKey("OwnerSubjectId");

                    b.HasOne("AuthorizationService.Infrastructure.Persistence.Entities.ResourceType", "ResourceType")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerSubject");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.HasOne("AuthorizationService.Infrastructure.Persistence.Entities.ResourceType", "ResourceType")
                        .WithMany("Roles")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.RolePermission", b =>
                {
                    b.HasOne("AuthorizationService.Infrastructure.Persistence.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthorizationService.Infrastructure.Persistence.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.SubjectRole", b =>
                {
                    b.HasOne("AuthorizationService.Infrastructure.Persistence.Entities.Resource", "Resource")
                        .WithMany("SubjectRoles")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthorizationService.Infrastructure.Persistence.Entities.Role", "Role")
                        .WithMany("SubjectRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthorizationService.Infrastructure.Persistence.Entities.Subject", "Subject")
                        .WithMany("SubjectRoles")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Role");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.Resource", b =>
                {
                    b.Navigation("SubjectRoles");
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.ResourceType", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Resources");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("SubjectRoles");
                });

            modelBuilder.Entity("AuthorizationService.Infrastructure.Persistence.Entities.Subject", b =>
                {
                    b.Navigation("Resources");

                    b.Navigation("SubjectRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
